language: cpp
compiler: gcc
dist: trusty

env:
  global:
    - secure: "ae+tdrAhjVLzsGvM1D0FeLttN94m8W61tOqbFuzvIpY/Uo63zFUy18ewn7s0pTVunGWFyGnyfW6S6drN18OUtWhCEp0dLutCfBD8padt2cmhWKl9ilRn+XfjOHiKdqxx8rwi7PX5J2XPOMX5VDxBlXV43whtwgQC5pEBl3+aNIk="
    - CXX=g++-4.8 CC=gcc-4.8 EIGEN_VERSION=3.1.0 EIGEN_HASH=ca142d0540d3 MSGPACK_C_VERSION="1.4.2"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - wget
      - automake
      - libtool
      - mpich2
      - gcc-4.8
      - g++-4.8
      - libboost1.54-all-dev
      - libzmq3-dev
      - libgflags-dev
      - libgoogle-glog-dev

before_install:
  - sudo add-apt-repository -y ppa:andykimpe/cmake;
  - sudo apt-get install -yqq cmake;

install:
  - cd /tmp
  - wget -O "/tmp/msgpack-c-${MSGPACK_C_VERSION}.tar.gz"
    "https://github.com/msgpack/msgpack-c/archive/cpp-${MSGPACK_C_VERSION}.tar.gz"
  - tar -zxvf "/tmp/msgpack-c-${MSGPACK_C_VERSION}.tar.gz" "msgpack-c-cpp-${MSGPACK_C_VERSION}"
  - cd "/tmp/msgpack-c-cpp-${MSGPACK_C_VERSION}"
  - ./bootstrap
  - ./configure
  - make
  - sudo make install
  - cd /tmp && rm -rf /tmp/msgpack-c*
  - wget -O "$EIGEN_VERSION.tar.gz" "http://bitbucket.org/eigen/eigen/get/${EIGEN_VERSION}.tar.gz"
  - tar -zxvf "$EIGEN_VERSION.tar.gz" "eigen-eigen-${EIGEN_HASH}"
  - mkdir -p "/tmp/eigen-eigen-${EIGEN_HASH}/build"
  - cd "/tmp/eigen-eigen-${EIGEN_HASH}/build"
  - cmake ..
  - make
  - sudo make install
  - cd /tmp && rm -rf /tmp/eigen*

before_script:
  - cd $TRAVIS_BUILD_DIR && mkdir build && cd build && cmake ..
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt

after_failure:
  - "cat /home/travis/build/douban/paracel/build/CMakeFiles/CMakeError.log"

script:
  - wget https://scan.coverity.com/download/linux64 --post-data "token=Igp_zlddSe0WOmJrNmZ-mg&project=douban%2Fparacel" -O coverity_tool.tgz
  - tar zxvf coverity_tool.tgz
  - $PWD/cov-analysis-linux64-*/bin/cov-build --dir cov-int make -j$(nproc)
  - tar czvf cov.tgz cov-int
  - "curl --form token=Igp_zlddSe0WOmJrNmZ-mg --form email=xunzhangthu@gmail.com --form file=@cov.tgz --form version=0.3.0 --form description=paracel https://scan.coverity.com/builds?project=douban%2Fparacel"

branches:
  only:
      - coverity_scan
